[package]
name = "ansi_brush"
version = "0.0.1"
edition = "2021"
description = "ANSI Styling"
license = "MIT"
keywords = ["ansi", "color", "colour", "terminal", "styling", "styles"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]